In [18]:
import pandas as pd
pd.set_option('display.max_columns', None)
from datetime import datetime

In [6]:
crashes = pd.read_csv("washington_crashes.csv")

/var/folders/0r/74g1680s6rz9r8mbc5tx0_0c0000gn/T/ipykernel_16121/792997793.py:1: DtypeWarning: Columns (0: A/B, 1: MISC TRAFFICWAY TYPE, 2: VEH 2 CONDITION 2, 3: VEH 2 CONDITION 3, 4: VEH 3 CONDITION 2, 5: VEH 3 CONDITION 3, 6: VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3, 7: VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2, 8: VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3, 9: VEH 3 MOTORCYCLE PASSENGER HELMET USAGE, 10: VEH 3 MOTORCYCLE PASSENGER INJURY TYPE, 11: UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 2, 12: UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 3, 13: UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2, 14: UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3, 15: UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1) have mixed types. Specify dtype option on import or set low_memory=False.
  crashes = pd.read_csv("washington_crashes.csv")

In [48]:
crashes['YEAR'].unique()

array([2015, 2025, 2024, 2017, 2023, 2019, 2026, 2013, 2021, 2016, 2011,
       2022, 2012, 2018, 2020, 2010, 2014])

In [29]:
for x in crashes.index:
    state_id = 53
    state_accident_id = crashes['REPORT NUMBER'][x]
    city = crashes['CITY'][x]
    if pd.isnull(city):
        city = None
    county = crashes['COUNTY'][x]
    street_1 = crashes['PRIMARY TRAFFICWAY'][x]
    street_2 = crashes['INTERSECTING TRAFFICWAY'][x]
    if pd.isnull(street_2):
        street_2 = None
    death_count = crashes['TOTAL FATALITIES'][x]
    severe_injury_count = crashes['TOTAL SERIOUS INJURIES'][x]
    lat = crashes['Latitude'][x]
    lon = crashes['Longitude'][x]
    crash_type = crashes['FIRST COLLISION TYPE / OBJECT STRUCK'][x]
    if pd.notnull(crashes['SECOND COLLISION TYPE / OBJECT STRUCK'][x]):
        crash_type += " - " + crashes['SECOND COLLISION TYPE / OBJECT STRUCK'][x]
    if pd.notnull(crashes['LIGHTING CONDITIONS'][x]):
        crash_type += " - " + crashes['LIGHTING CONDITIONS'][x]
    if crashes['HIT & RUN'][x] == "Yes":
        crash_type = "Hit and Run - " + crash_type
    date = crashes['DATE'][x]
    month = date.split("/")[0].zfill(2)
    day = date.split("/")[1].zfill(2)
    year = date.split("/")[2]
    dt = datetime.strptime(f"{year}-{month}-{day}T00:00:00", "%Y-%m-%dT%H:%M:%S")
    total_vehicles = crashes['TOTAL VEHICLES'][x]
    total_nonmotorists = crashes['TOTAL PEDESTRIANS INVOLVED'][x] + crashes['TOTAL BICYCLISTS INVOLVED'][x]
    #vehicles
    if pd.notnull(crashes['VEH 1 TYPE'][x]):
        body_type = f"{crashes['VEH 1 TYPE'][x]} - {crashes['VEH 1 STYLE'][x]}"
        make = crashes['VEH 1 MAKE'][x]
        model = crashes['VEH 1 MODEL'][x]
        vehicle_number = 1
        #driver
        age = crashes['VEH 1 MV DRIVER AGE'][x]
        sex = crashes['VEH 1 MV DRIVER GENDER'][x]
        inj_sev = crashes['VEH 1 MV DRIVER INJURY TYPE'][x]
        
    if pd.notnull(crashes['UNIT 2 PEDESTRIAN ACTION'][x]):
        ped_age = crashes['UNIT 2 PEDESTRIAN AGE'][x]
        ped_sex = crashes['UNIT 2 PEDESTRIAN GENDER'][x]
        ped_inj_sev = crashes['UNIT 2 PEDESTRIAN INJURY TYPE'][x]
        
    if pd.notnull(crashes['UNIT 1 BICYCLIST ACTION'][x]):
        bike_age = crashes['UNIT 1 BICYCLIST AGE'][x]
        bike_sex = crashes['UNIT 1 BICYCLIST GENDER'][x]
        bike_inj_sev = crashes['UNIT 1 BICYCLIST INJURY TYPE'][x]
    break

In [38]:
pd.isnull(NaN)

NameError: name 'NaN' is not defined

In [25]:
c

<StringArray>
[                                            nan,
 'Pickup,Panel Truck or Vanette under 10,000 lb',
                                 'Passenger Car',
                  'Truck Tractor & Semi-Trailer',
                                    'Motorcycle',
                                         'Other',
           'Truck - Double Trailer Combinations',
                       'Truck (Flatbad,Van,etc)',
            'Farm Tractor and/or Farm equipment',
                               'Railway Vehicle',
                                    'Not Stated',
                               'Truck & Trailer',
                                  'Scooter Bike',
                                         'Moped',
                            'Bus or Motor Stage',
                                 'Truck Tractor',
                                    'School Bus',
                                     'Golf Cart',
                                          'Taxi']
Length: 19, dtype: str

In [ ]:

class InjuryVehicle(models.Model):
    injury_accident = models.ForeignKey(InjuryAccident, on_delete=models.CASCADE)
    vehicle_number = models.PositiveSmallIntegerField(null=False, blank=False)
    make = models.TextField(null=True, blank=True)
    model = models.TextField(null=True, blank=True)
    body_type = models.TextField(null=True, blank=True)
    violation = models.TextField(null=True, blank=True)
    hit_and_run = models.BooleanField(default=False)

class InjuryPerson(models.Model):
    injury_accident = models.ForeignKey(InjuryAccident, on_delete=models.CASCADE)
    injury_vehicle = models.ForeignKey(InjuryVehicle, null=True, blank=True, on_delete = models.CASCADE)
    age = models.PositiveSmallIntegerField(null = True, blank = True)
    #p6 
    sex = models.CharField(max_length=64, null=True, blank=True)
    person_type = models.CharField(max_length=256,null=True, blank=True)
    #p8 injury_severity
    injury_severity_choices = [
        (0, 'No Apparent Injury (O)'),
        (1, 'Possible Injury (C)'),
        (2, 'Suspected Minor Injury (B)'),
        (3, 'Suspected Serious Injury (A)'),
        (4, 'Fatal Injury (K)'),
        (5, 'Injured, Severity Unknown (U) (Since 1978)'),
        (6, 'Died Prior to Crash'),
        (9, 'Unknown/Not Reported')
    ]			
    injury_severity = models.PositiveSmallIntegerField(choices=injury_severity_choices, default=9)

In [40]:
crashes

,JURISDICTION,COUNTY,CITY,REPORT NUMBER,INDEXED PRIMARY TRAFFICWAY,PRIMARY TRAFFICWAY,BLOCK NUMBER,MILEPOST,A/B,INTERSECTING TRAFFICWAY,DIST FROM REF POINT,MI or FT,COMP DIR FROM REF POINT,REFERENCE POINT NAME,DATE,YEAR,MOST SEVERE SOBRIETY TYPE,MOST SEVERE INJURY TYPE,TOTAL CRASHES,FATAL CRASHES,SERIOUS INJURY CRASHES,MINOR INJURY CRASHES,POSSIBLE INJURY CRASHES,PDO - NO INJURY CRASHES,TOTAL FATALITIES,TOTAL SERIOUS INJURIES,TOTAL MINOR INJURIES,TOTAL POSSIBLE INJURIES,TOTAL VEHICLES,TOTAL PEDESTRIANS INVOLVED,TOTAL BICYCLISTS INVOLVED,WORKZONE,FIRST COLLISION TYPE / OBJECT STRUCK,SECOND COLLISION TYPE / OBJECT STRUCK,JUNCTION RELATIONSHIP,WEATHER,ROAD SURFACE CONDITIONS,Roadway Characteristic,LIGHTING CONDITIONS,MISC TRAFFICWAY TYPE,"COUNTY RD ONLY, INTERSECTING CO RD MILEPOST",SR ONLY ACCUMULATIVE ROUTE MILEPOST (ARM),SR ONLY HISTORY / SUSPENSE IND,"FIRST IMPACT LOCATION (City St, County Rd & Misc 2010 forward, State Routes indefinite)",SECOND IMPACT LOCATION (2010 forward for All Jurisdictions),VEH 1 TYPE,VEH 1 MAKE,VEH 1 MODEL,VEH 1 STYLE,VEH 1 ACTION,VEH 1 COMPASS DIRECTION FROM,VEH 1 COMPASS DIRECTION TO,VEH 1 USAGE,VEH 1 TRAFFIC CONTROL,VEH 1 POSTED SPEED,VEH 1 COMMERCIAL CLASS,VEH 1 COMMERCIAL GVWR,VEH 1 COMMERCIAL AXLE COUNT,VEH 1 CLASSIFICATION,VEH 1 CONDITION 1,VEH 1 CONDITION 2,VEH 1 CONDITION 3,VEH 2 TYPE,VEH 2 MAKE,VEH 2 MODEL,VEH 2 STYLE,VEH 2 ACTION,VEH 2 COMPASS DIRECTION FROM,VEH 2 COMPASS DIRECTION TO,VEH 2 USAGE,VEH 2 TRAFFIC CONTROL,VEH 2 POSTED SPEED,VEH 2 COMMERCIAL CLASS,VEH 2 COMMERCIAL GVWR,VEH 2 COMMERCIAL AXLE COUNT,VEH 2 CLASSIFICATION,VEH 2 CONDITION 1,VEH 2 CONDITION 2,VEH 2 CONDITION 3,VEH 3 TYPE,VEH 3 MAKE,VEH 3 STYLE,VEH 3 MODEL,VEH 3 ACTION,VEH 3 COMPASS DIRECTION FROM,VEH 3 COMPASS DIRECTION TO,VEH 3 USAGE,VEH 3 TRAFFIC CONTROL,VEH 3 POSTED SPEED,VEH 3 COMMERCIAL CLASS,VEH 3 COMMERCIAL GVWR,VEH 3 COMMERCIAL AXLE COUNT,VEHICLE 3 CLASSIFICATION,VEH 3 CONDITION 1,VEH 3 CONDITION 2,VEH 3 CONDITION 3,VEH 1 MV DRIVER AGE,VEH 1 MV DRIVER GENDER,VEH 1 MV DRIVER INJURY TYPE,VEH 1 MV DRIVER CONTRIBUTING CIRCUMSTANCE 1,VEH 1 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2,VEH 1 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3,VEH 1 MOTORCYCLE DRIVER HELMET USAGE,VEH 1 MOTORCYCLE PASSENGER HELMET USAGE,VEH 1 MOTORCYCLE PASSENGER INJURY TYPE,VEH 1 MV DRIVER RESTRAINT,VEH 1 MV DRIVER EJECTION,VEH 2 MV DRIVER AGE,VEH 2 MV DRIVER GENDER,VEH 2 MV DRIVER INJURY TYPE,VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 1,VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2,VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3,VEH 2 MOTORCYCLE DRIVER HELMET USAGE,VEH 2 MOTORCYCLE PASSENGER HELMET USAGE,VEH 2 MOTORCYCLE PASSENGER INJURY TYPE,VEH 2 MV DRIVER RESTRAINT,VEH 2 MV DRIVER EJECTION,VEH 3 MV DRIVER AGE,VEH 3 MV DRIVER GENDER,VEH 3 MV DRIVER INJURY TYPE,VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 1,VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2,VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3,VEH 3 MOTORCYCLE DRIVER HELMET USAGE,VEH 3 MOTORCYCLE PASSENGER HELMET USAGE,VEH 3 MOTORCYCLE PASSENGER INJURY TYPE,VEH 3 MV DRIVER RESTRAINT,VEH 3 MV DRIVER EJECTION,UNIT 2 PEDESTRIAN ACTION,UNIT 2 PEDESTRIAN AGE,UNIT 2 PEDESTRIAN CLOTHING VISIBILITY,UNIT 2 PEDESTRIAN GENDER,UNIT 2 PEDESTRIAN INJURY TYPE,UNIT 2 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 1,UNIT 2 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 2,UNIT 2 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 3,UNIT 2 PEDESTRIAN WAS USING,UNIT 2 PEDESTRIAN STATUS,UNIT 3 PEDESTRIAN ACTION,UNIT 3 PEDESTRIAN AGE,UNIT 3 PEDESTRIAN CLOTHING VISIBILITY,UNIT 3 PEDESTRIAN GENDER,UNIT 3 PEDESTRIAN INJURY TYPE,UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 1,UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 2,UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 3,UNIT 3 PEDESTRIAN WAS USING,UNIT 3 PEDESTRIAN STATUS,UNIT 1 BICYCLIST ACTION,UNIT 1 BICYCLIST AGE,UNIT 1 BICYCLIST CLOTHING VISIBILITY,UNIT 1 BICYCLIST GENDER,UNIT 1 BICYCLIST INJURY TYPE,UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1,UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2,UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3,UNIT 1 BICYCLIST WAS USING,UNIT 2 BICYCLIST ACTION,UNIT 2 BICYCLIST AGE,UNIT 2 BICYCLIST CLOTHING VISIBILITY,UNIT 2 BICYCLIST GENDER,UNIT 2 BICYCLIST INJURY TYPE,UNIT 2 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1,UNIT 2 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2,UNIT 2 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3,UNIT 2 BICYCLIST WAS USING,UNIT 3 BICYCLIST ACTION,UNIT 3 BICYCLIST AGE,UNIT 3 BICYCLIST CLOTHING VISIBILITY,UNIT 3 BICYCLIST GENDER,UNIT 3 BICYCLIST INJURY TYPE,UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1,UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2,UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3,UNIT 3 BICYCLIST WAS USING,HIT & RUN,NON-REPORTABLE,WA STATE PLANE SOUTH - X,WA STATE PLANE SOUTH - Y,Latitude,Longitude
0,City Street,Adams,Othello,E468501,ASH ST,ASH ST,1200.0,NaN,NaN,S 12TH AVE,NaN,NaN,NaN,NaN,10/5/2015,2015,Had NOT Been Drinking,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,1,1,0,NaN,Vehicle going straight hits pedestrian,NaN,At Intersection and Related,Clear or Partly Cloudy,Dry,Straight & Level,Daylight,NaN,NaN,NaN,No,Lane of Primary Trafficway,NaN,Passenger Car,ACURA,3.2CL,Coupe,Going Straight Ahead,East,West,NaN,No Traffic Control,20.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Female,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Xing at Intersection - No Signal,6.0,Dark,Female,Suspected Serious Injury,Inattention,NaN,NaN,Unmarked X walk,Person on Foot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1976487.05,544677.07,46.819119,-119.157526
1,City Street,Adams,Othello,EF66351,E HAMLET ST,E HAMLET ST,400.0,NaN,NaN,NaN,80.0,F,E,N 4TH AVE,1/27/2025,2025,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,1,0,0,NaN,"Person fell, jumped or was pushed from vehicle",NaN,Not at Intersection and Not Related,Clear,Dry,Straight & Grade,Dark-Street Lights On,NaN,NaN,NaN,No,Lane of Primary Trafficway,NaN,Passenger Car,NISSAN,SENTRA,Sedan,Starting From Parked Position,West,East,NaN,No Traffic Control,25.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0,Male,Unknown,Other Contributing Circ Not Listed,NaN,NaN,NaN,NaN,NaN,Unknown,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Reportable,1973473.49,548690.15,46.830261,-119.169291
2,City Street,Adams,Othello,EE93057,E JUNIPER ST,E JUNIPER ST,700.0,NaN,NaN,NaN,181.0,F,W,S 8TH AVE,6/2/2024,2024,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,1,0,4,0,0,NaN,One parked--one moving,One parked--one moving,Not at Intersection and Not Related,Clear,Dry,Straight & Level,Dark-Street Lights On,NaN,NaN,NaN,No,Outside Shoulder of Primary Trafficway,Outside Shoulder of Primary Trafficway,"Pickup,Panel Truck or Vanette under 10,000 lb",NISSAN,FRONTIER,Pickup,Going Straight Ahead,West,East,NaN,No Traffic Control,25.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",SUBARU,FORESTER,UTILITY,"Legally Parked, Unoccupied",NaN,NaN,"Vanette Under 10,000 lb",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger Car,CHEVROLET,Sedan,CRUZE,"Legally Parked, Unoccupied",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,Male,Suspected Serious Injury,Under Influence of Alcohol,Exceeding Stated Speed Limit,NaN,NaN,NaN,NaN,No Restraints Used,Partially Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1974808.42,545750.33,46.822140,-119.164157
3,City Street,Adams,Othello,EF98910,E LARCH ST,E LARCH ST,1001.0,NaN,NaN,S 11TH AVE,NaN,NaN,NaN,NaN,5/30/2025,2025,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,1,1,0,NaN,Vehicle going straight hits pedestrian,NaN,Traffic Calming Circle,Clear,Dry,Straight & Level,Daylight,NaN,NaN,NaN,No,Lane of Primary Trafficway,NaN,Not Stated,NaN,NaN,NaN,Other*,West,East,NaN,No Traffic Control,25.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown Distraction,Did Not Grant R/W to Non Motorist,NaN,NaN,NaN,NaN,Unknown,Unknown if Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Xing at Intersection - No Signal,17.0,Light,Female,Suspected Serious Injury,NaN,NaN,NaN,Marked X walk,Person on Foot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Reportable,1976074.07,546510.59,46.824165,-119.159051
4,City Street,Adams,Othello,EG24243,E MADERA ST,E MADERA ST,1900.0,NaN,NaN,NaN,115.0,F,NW,W CEMETARY RD,8/29/2025,2025,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,2,0,0,NaN,One parked--one moving,NaN,Not at Intersection and Not Related,Clear,Dry,Straight & Level,Dark-Street Lights On,NaN,NaN,NaN,No,Outside Shoulder of Primary Trafficway,NaN,Passenger Car,HONDA,FIT,Hatchback,Going Straight Ahead,South,North,NaN,No Traffic Control,25.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",GMC,SIERRA,Pickup,"Illegally Parked, Unoccupied",NaN,East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0,Male,Suspected Serious Injury,Under Influence of Alcohol,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown if Ejected,NaN,NaN,NaN,Other Contributing Circ Not Listed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Reportable,1979149.01,545413.64,46.821014,-119.146844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43542,State Route,Yakima,NaN,EE85571,823,823,NaN,2.82,NaN,NaN,NaN,NaN,NaN,NaN,5/28/2024,2024,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,2,0,0,NaN,Entering at angle,NaN,At Intersection and Related,Clear or Partly Cloudy,Dry,Straight & Grade,Dusk,NaN,NaN,3.64,No,Lane 1 Decreasing Milepost,NaN,Motorcycle,KAWASAKI,EX650,"Motorcycle, Motorbike, or Minibike",Going Straight Ahead,South,North,NaN,No Traffic Control,40.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,Passenger Car,FORD,F150,Pickup,Stopped at Signal or Stop Sign,East,Vehicle Stopped,NaN,Stop Sign,40.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,Male,Suspected Serious Injury,Under Influence of Alcohol,Exceeding Stated Speed Limit,Operating Recklessly or Aggressively,DOT Compliant Motorc,NaN,NaN,Not Equipped,Totally Ejected,69.0,Male,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1635939.52,487856.81,46.671154,-120.517835
43543,State Route,Yakima,NaN,E326043,823,823,NaN,2.82,NaN,NaN,NaN,NaN,NaN,NaN,5/2/2014,2014,Had NOT Been Drinking,Suspected Serious Injury,1,0,1,0,0,0,0,2,0,0,2,0,0,NaN,From opposite direction - one left turn - one ...,NaN,At Intersection and Related,Clear or Partly Cloudy,Dry,Straight & Level,Dark-No Street Lights,NaN,NaN,3.64,No,Lane 1 Increasing Milepost,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",GMC,YUKON,WAGON 4 DOOR,Making Left Turn,North,East,"Vanette Under 10,000 lb",Yield,35.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,Passenger Car,FORD,FESTIVA,HATCHBACK 2 DOOR,Going Straight Ahead,South,North,NaN,No Traffic Control,35.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Improper Turn/Merge,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown if Ejected,19.0,Male,Suspected Serious Injury,NaN,NaN,NaN,NaN,NaN,NaN,Shoulder Belt Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Reportable,1635937.58,487861.82,46.671168,-120.517843
43544,State Route,Yakima,NaN,EB35531,NB SR823,823,NaN,4.44,NaN,NaN,NaN,NaN,NaN,NaN,5/15/2021,2021,NaN,Dead at Scene,1,1,0,0,0,0,1,1,1,1,3,1,0,Within WorkZone,From same direction - both going straight - on...,Vehicle going straight hits pedestrian,Not at Intersection and Not Related,Clear,Dry,Straight & Grade,Dark-Street Lights On,NaN,NaN,5.26,No,Right Shoulder Increasing Milepost,Right Shoulder Increasing Milepost,Passenger Car,VOLKSWAGEN,PASSAT,Sedan,Going Straight Ahead,Southwest,Northeast,NaN,Officer/Flagger,55.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,Truck Tractor & Semi-Trailer,PETERBILT,365,Dump Truck,Stopped for Traffic,Southwest,Vehicle Stopped,Dump Truck,Officer/Flagger,35.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",FORD,Pickup,RANGER,"Legally Parked, Unoccupied",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,NaN,Possible Injury,Under Influence of Alcohol,Under Influence of Drugs,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,55.0,Male,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1643319.60,491009.42,46.679800,-120.488434
43545,State Route,Yakima,NaN,EB33270,823,823,NaN,4.47,NaN,NaN,NaN,NaN,NaN,NaN,5/24/2021,2021,NaN,Dead at Scene,1,1,0,0,0,0,1,0,1,0,2,0,0,NaN,From opposite direction - both moving - head-on,Vehicle overturned,Not at Intersection and Not Related,Clear,Dry,Curve & Grade,Daylight,NaN,NaN,5.29,No,Lane 1 Decreasing Milepost,Lane 1 Decreasing Milepost,Passenger Car,FORD,ESCORT,WAGON,Overtaking and Passing,South,North,NaN,No Traffic Control,55.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",FORD,F350,Pickup,Other*,North,South,NaN,No Traffic Control,55.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,Male,Dead at Scene,Under Influence of Drugs,Unknown Distraction,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,44.0,Male,Suspected Minor Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1643443.26,491057.59,46.679932,-120.487942
43546,State Route,Yakima,NaN,EB96427,823,823,NaN,4.52,NaN,NaN,NaN,NaN,NaN,NaN,11/17/2021,2021,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,1,1,0,NaN,Vehicle going straight hits pedestrian,NaN,Not at Intersection and Not Related,Clear,Dry,Straight & Grade,Dark-No Street Lights,NaN,NaN,5.34,No,Lane 1 Decreasing Milepost,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",BUICK,ENCLAVE,UTILITY,Going Straight Ahead,North,South,"Vanette Under 10,000 lb",No Traffic Control,55.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,Male,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fell or Pushed Into Path of Vehicle,NaN,Dark,Male,Suspected Serious Injury,Other Contributing Circ Not Listed,NaN,NaN,Roadway,Person on Foot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1643684.93,491152.43,46.680192,-120.486979

In [41]:
crashes['VEH 1 MV DRIVER INJURY TYPE'].unique()

<StringArray>
[      'No Apparent Injury',                  'Unknown',
 'Suspected Serious Injury',            'Dead at Scene',
   'Suspected Minor Injury',          'Possible Injury',
                        nan,         'Died at Hospital',
          'Dead on Arrival',     'Non-Traffic Fatality',
       'Non-Traffic Injury']
Length: 11, dtype: str

In [ ]:
def get_inj_sev(sev_str):
    if sev_str in ["Dead on Arrival", "Dead at Scene", "Died at Hospital"]:
        return 4
    if sev_str in ["Suspected Serious Injury"]:
        return 3
    if sev_str in ["Suspected Minor Injury"]:
        return 2
    if sev_str in ["Possible Injury"]:
        return 1
    if sev_str in ["No Apparent Injury"]:
        return 0
    if sev_str in ["'Non-Traffic Fatality"]:
        return 6
    return 9

In [42]:
crashes[crashes['VEH 1 MV DRIVER INJURY TYPE']=="Non-Traffic Fatality"]

,JURISDICTION,COUNTY,CITY,REPORT NUMBER,INDEXED PRIMARY TRAFFICWAY,PRIMARY TRAFFICWAY,BLOCK NUMBER,MILEPOST,A/B,INTERSECTING TRAFFICWAY,DIST FROM REF POINT,MI or FT,COMP DIR FROM REF POINT,REFERENCE POINT NAME,DATE,YEAR,MOST SEVERE SOBRIETY TYPE,MOST SEVERE INJURY TYPE,TOTAL CRASHES,FATAL CRASHES,SERIOUS INJURY CRASHES,MINOR INJURY CRASHES,POSSIBLE INJURY CRASHES,PDO - NO INJURY CRASHES,TOTAL FATALITIES,TOTAL SERIOUS INJURIES,TOTAL MINOR INJURIES,TOTAL POSSIBLE INJURIES,TOTAL VEHICLES,TOTAL PEDESTRIANS INVOLVED,TOTAL BICYCLISTS INVOLVED,WORKZONE,FIRST COLLISION TYPE / OBJECT STRUCK,SECOND COLLISION TYPE / OBJECT STRUCK,JUNCTION RELATIONSHIP,WEATHER,ROAD SURFACE CONDITIONS,Roadway Characteristic,LIGHTING CONDITIONS,MISC TRAFFICWAY TYPE,"COUNTY RD ONLY, INTERSECTING CO RD MILEPOST",SR ONLY ACCUMULATIVE ROUTE MILEPOST (ARM),SR ONLY HISTORY / SUSPENSE IND,"FIRST IMPACT LOCATION (City St, County Rd & Misc 2010 forward, State Routes indefinite)",SECOND IMPACT LOCATION (2010 forward for All Jurisdictions),VEH 1 TYPE,VEH 1 MAKE,VEH 1 MODEL,VEH 1 STYLE,VEH 1 ACTION,VEH 1 COMPASS DIRECTION FROM,VEH 1 COMPASS DIRECTION TO,VEH 1 USAGE,VEH 1 TRAFFIC CONTROL,VEH 1 POSTED SPEED,VEH 1 COMMERCIAL CLASS,VEH 1 COMMERCIAL GVWR,VEH 1 COMMERCIAL AXLE COUNT,VEH 1 CLASSIFICATION,VEH 1 CONDITION 1,VEH 1 CONDITION 2,VEH 1 CONDITION 3,VEH 2 TYPE,VEH 2 MAKE,VEH 2 MODEL,VEH 2 STYLE,VEH 2 ACTION,VEH 2 COMPASS DIRECTION FROM,VEH 2 COMPASS DIRECTION TO,VEH 2 USAGE,VEH 2 TRAFFIC CONTROL,VEH 2 POSTED SPEED,VEH 2 COMMERCIAL CLASS,VEH 2 COMMERCIAL GVWR,VEH 2 COMMERCIAL AXLE COUNT,VEH 2 CLASSIFICATION,VEH 2 CONDITION 1,VEH 2 CONDITION 2,VEH 2 CONDITION 3,VEH 3 TYPE,VEH 3 MAKE,VEH 3 STYLE,VEH 3 MODEL,VEH 3 ACTION,VEH 3 COMPASS DIRECTION FROM,VEH 3 COMPASS DIRECTION TO,VEH 3 USAGE,VEH 3 TRAFFIC CONTROL,VEH 3 POSTED SPEED,VEH 3 COMMERCIAL CLASS,VEH 3 COMMERCIAL GVWR,VEH 3 COMMERCIAL AXLE COUNT,VEHICLE 3 CLASSIFICATION,VEH 3 CONDITION 1,VEH 3 CONDITION 2,VEH 3 CONDITION 3,VEH 1 MV DRIVER AGE,VEH 1 MV DRIVER GENDER,VEH 1 MV DRIVER INJURY TYPE,VEH 1 MV DRIVER CONTRIBUTING CIRCUMSTANCE 1,VEH 1 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2,VEH 1 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3,VEH 1 MOTORCYCLE DRIVER HELMET USAGE,VEH 1 MOTORCYCLE PASSENGER HELMET USAGE,VEH 1 MOTORCYCLE PASSENGER INJURY TYPE,VEH 1 MV DRIVER RESTRAINT,VEH 1 MV DRIVER EJECTION,VEH 2 MV DRIVER AGE,VEH 2 MV DRIVER GENDER,VEH 2 MV DRIVER INJURY TYPE,VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 1,VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2,VEH 2 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3,VEH 2 MOTORCYCLE DRIVER HELMET USAGE,VEH 2 MOTORCYCLE PASSENGER HELMET USAGE,VEH 2 MOTORCYCLE PASSENGER INJURY TYPE,VEH 2 MV DRIVER RESTRAINT,VEH 2 MV DRIVER EJECTION,VEH 3 MV DRIVER AGE,VEH 3 MV DRIVER GENDER,VEH 3 MV DRIVER INJURY TYPE,VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 1,VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 2,VEH 3 MV DRIVER CONTRIBUTING CIRCUMSTANCE 3,VEH 3 MOTORCYCLE DRIVER HELMET USAGE,VEH 3 MOTORCYCLE PASSENGER HELMET USAGE,VEH 3 MOTORCYCLE PASSENGER INJURY TYPE,VEH 3 MV DRIVER RESTRAINT,VEH 3 MV DRIVER EJECTION,UNIT 2 PEDESTRIAN ACTION,UNIT 2 PEDESTRIAN AGE,UNIT 2 PEDESTRIAN CLOTHING VISIBILITY,UNIT 2 PEDESTRIAN GENDER,UNIT 2 PEDESTRIAN INJURY TYPE,UNIT 2 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 1,UNIT 2 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 2,UNIT 2 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 3,UNIT 2 PEDESTRIAN WAS USING,UNIT 2 PEDESTRIAN STATUS,UNIT 3 PEDESTRIAN ACTION,UNIT 3 PEDESTRIAN AGE,UNIT 3 PEDESTRIAN CLOTHING VISIBILITY,UNIT 3 PEDESTRIAN GENDER,UNIT 3 PEDESTRIAN INJURY TYPE,UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 1,UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 2,UNIT 3 PEDESTRIAN CONTRIBUTING CIRCUMSTANCE 3,UNIT 3 PEDESTRIAN WAS USING,UNIT 3 PEDESTRIAN STATUS,UNIT 1 BICYCLIST ACTION,UNIT 1 BICYCLIST AGE,UNIT 1 BICYCLIST CLOTHING VISIBILITY,UNIT 1 BICYCLIST GENDER,UNIT 1 BICYCLIST INJURY TYPE,UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1,UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2,UNIT 1 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3,UNIT 1 BICYCLIST WAS USING,UNIT 2 BICYCLIST ACTION,UNIT 2 BICYCLIST AGE,UNIT 2 BICYCLIST CLOTHING VISIBILITY,UNIT 2 BICYCLIST GENDER,UNIT 2 BICYCLIST INJURY TYPE,UNIT 2 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1,UNIT 2 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2,UNIT 2 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3,UNIT 2 BICYCLIST WAS USING,UNIT 3 BICYCLIST ACTION,UNIT 3 BICYCLIST AGE,UNIT 3 BICYCLIST CLOTHING VISIBILITY,UNIT 3 BICYCLIST GENDER,UNIT 3 BICYCLIST INJURY TYPE,UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 1,UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 2,UNIT 3 BICYCLIST CONTRIBUTING CIRCUMSTANCE 3,UNIT 3 BICYCLIST WAS USING,HIT & RUN,NON-REPORTABLE,WA STATE PLANE SOUTH - X,WA STATE PLANE SOUTH - Y,Latitude,Longitude
1705,State Route,Chelan,NaN,EA35914,2,2,NaN,104.460,NaN,NaN,NaN,NaN,NaN,NaN,5/20/2020,2020,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,2,0,0,NaN,From opposite direction - both going straight ...,From opposite direction - all others,Not at Intersection and Not Related,Clear,Dry,Straight & Level,Daylight,NaN,NaN,104.52,No,Lane 1 Increasing Milepost,Right Shoulder Increasing Milepost,Passenger Car,CHRYSLER,PT CRUISER,VAN PASSENGER,Going Straight Ahead,East,West,NaN,No Traffic Control,50.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",GMC,SIERRA,Pickup,Going Straight Ahead,West,East,NaN,No Traffic Control,50.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,Male,Non-Traffic Fatality,Other Contributing Circ Not Listed,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,67.0,Male,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1617285.410,811882.750,47.559521,-120.593677
2282,State Route,Clallam,NaN,E554977,SR 101,101,NaN,271.700,NaN,NaN,NaN,NaN,NaN,NaN,6/10/2016,2016,Had NOT Been Drinking,Suspected Serious Injury,1,0,1,0,0,0,0,1,1,0,4,0,0,NaN,From opposite direction - both moving - head-on,From opposite direction - all others,Not at Intersection and Not Related,Raining,Wet,Curve & Level,Daylight,NaN,NaN,270.71,No,Lane 1 Decreasing Milepost,Lane 1 Decreasing Milepost,"Pickup,Panel Truck or Vanette under 10,000 lb",TOYOTA,TUNDRA,Pickup,Going Straight Ahead,Southwest,Northeast,NaN,No Traffic Control,55.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",FORD,NaN,Van,Going Straight Ahead,Northeast,Southwest,"Vanette Under 10,000 lb",No Traffic Control,55.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,Truck Tractor & Semi-Trailer,PETERBILT SEMI,TRACTOR TRK (DIESEL),NaN,Going Straight Ahead,Northeast,Southwest,Tanker Truck,No Traffic Control,55.0,Tractor/Semi-Trailer,54000.0,5.0,"Single vehicle w/GVWR of 26,001 lbs or more; o...",No Defects,NaN,NaN,79.0,Male,Non-Traffic Fatality,Over Center Line,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,61.0,Male,Suspected Serious Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,38.0,Male,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1030025.060,992153.310,48.027219,-122.994236
4707,State Route,Clark,NaN,EB25503,503,503,NaN,13.120,NaN,NaN,NaN,NaN,NaN,NaN,4/22/2021,2021,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,2,0,0,NaN,One parked--one moving,Roadway Ditch,Not at Intersection and Not Related,Overcast,Dry,Straight & Level,Daylight,NaN,NaN,12.90,No,Right Shoulder Increasing Milepost,Past Right Shoulder Increasing Milepost,"Pickup,Panel Truck or Vanette under 10,000 lb",CHEVROLET,BLAZER,UTILITY,Overtaking and Passing,South,North,"Vanette Under 10,000 lb",No Traffic Control,55.0,NaN,NaN,NaN,NaN,Other Defects,NaN,NaN,Passenger Car,SUZUKI,SAMURAI,Convertible,"Legally Parked, Occupied",South,North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0,Male,Non-Traffic Fatality,Operating Defective Equipment,Exceeding Reas. Safe Speed,Improper Passing,NaN,NaN,NaN,No Restraints Used,Not Ejected,46.0,Male,Suspected Serious Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1124397.460,194579.800,45.848749,-122.525138
11763,City Street,King,Seattle,ED47789,HARVARD AVE,HARVARD AVE,1500.0,NaN,NaN,NaN,30.0,F,N,E PINE ST,4/1/2023,2023,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,2,0,0,NaN,One parked--one moving,NaN,Not at Intersection and Not Related,Overcast,Dry,NaN,Daylight,NaN,NaN,NaN,No,Outside Shoulder of Primary Trafficway,NaN,Passenger Car,TOYOTA,NaN,Sedan,Going Straight Ahead,East,North,NaN,No Traffic Control,25.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,Passenger Car,TOYOTA,PRIUS,Hatchback,"Legally Parked, Occupied",Vehicle Stopped,North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,Male,Non-Traffic Fatality,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,30.0,Male,No Apparent Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1190995.750,837422.130,47.615338,-122.322138
15335,County Road,King,NaN,2545703,228 AVE SE,30790,NaN,0.529,NaN,NaN,NaN,NaN,NaN,NaN,9/12/2010,2010,HBD - Ability Impaired (tox test),Dead at Scene,1,1,0,0,0,0,1,0,0,0,1,0,1,NaN,Vehicle - Pedalcyclist,NaN,Not at Intersection and Not Related,Clear or Partly Cloudy,Dry,Straight & Level,Dark-No Street Lights,NaN,NaN,NaN,No,Lane of Primary Trafficway,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",GMC,SIERRA,CLUB CAB PICKUP,Going Straight Ahead,North,South,NaN,No Traffic Control,35.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,Male,Non-Traffic Fatality,Other Contributing Circ Not Listed,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Riding with Traffic,20.0,Dark,Male,Dead at Scene,Under Influence of Alcohol,NaN,NaN,Roadway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1258266.651,685609.648,47.203169,-122.037474
19443,State Route,King,NaN,EG58779,516,516,NaN,3.780,NaN,NaN,NaN,NaN,NaN,NaN,12/13/2025,2025,NaN,Dead at Scene,1,1,0,0,0,0,1,0,0,0,1,1,0,NaN,Vehicle going straight hits pedestrian,NaN,Not at Intersection and Not Related,Overcast,Dry,Curve & Level,Dark-Street Lights On,NaN,NaN,3.77,No,Lane 2 Decreasing Milepost,NaN,Not Stated,NaN,NaN,NaN,Negotiating a Curve,Southeast,Northwest,NaN,No Traffic Control,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non-Traffic Fatality,Other Contributing Circ Not Listed,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown if Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Xing - Non Intersection - No X Walk,55.0,Dark,Male,Dead at Scene,Unknown Distraction,Under Influence of Drugs,NaN,Roadway,Person on Foot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Reportable,1202298.170,749792.550,47.375880,-122.268365
21967,State Route,Kittitas,NaN,E297274,STATE ROUTE 97 SOUTH,97,NaN,140.800,NaN,NaN,NaN,NaN,NaN,NaN,12/28/2013,2013,Had NOT Been Drinking,Dead at Scene,1,1,0,0,0,0,1,0,0,0,1,0,0,NaN,Roadway Ditch,Vehicle overturned,Not at Intersection and Not Related,Clear or Partly Cloudy,Dry,Curve & Level,Daylight,NaN,NaN,125.58,No,Past Right Shoulder Decreasing Milepost,Past Right Shoulder Decreasing Milepost,Passenger Car,BUICK,LESABRE,Sedan 4 Dr,Going Straight Ahead,North,South,NaN,No Traffic Control,65.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,Male,Non-Traffic Fatality,Other Contributing Circ Not Listed,NaN,NaN,NaN,NaN,NaN,No Restraints Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1603269.590,639581.130,47.087085,-120.649119
22586,County Road,Lewis,NaN,EE76426,GORE RD,64003,NaN,2.804,NaN,NaN,NaN,NaN,NaN,NaN,5/9/2024,2024,NaN,Dead at Scene,1,1,0,0,0,0,1,1,0,0,1,0,0,NaN,Roadway Ditch,Tree or Stump (stationary),Not at Intersection and Not Related,Clear,Dry,Straight & Level,Daylight,NaN,NaN,NaN,No,Past the Outside Shoulder of Primary Trafficway,Past the Outside Shoulder of Primary Trafficway,"Pickup,Panel Truck or Vanette under 10,000 lb",CHEVROLET,GMT-400,Pickup,Going Straight Ahead,West,East,NaN,No Traffic Control,50.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,Male,Non-Traffic Fatality,Under Influence of Drugs,Exceeding Stated Speed Limit,NaN,NaN,NaN,NaN,No Restraints Used,Partially Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1096765.800,449834.180,46.546469,-122.660966
29538,State Route,Pierce,NaN,E171439,WB SR 302,302,NaN,15.230,NaN,NaN,NaN,NaN,NaN,NaN,5/21/2012,2012,Had NOT Been Drinking,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,2,0,0,NaN,From opposite direction - both moving - head-on,NaN,Not at Intersection and Not Related,Raining,Wet,Straight & Level,Daylight,NaN,NaN,15.23,No,Lane 1 Increasing Milepost,NaN,Passenger Car,HONDA,CIVIC,Sedan 4 Dr,Going Straight Ahead,East,West,NaN,No Traffic Control,40.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,Passenger Car,TOYOTA,COROLLA,Sedan 4 Dr,Going Straight Ahead,West,East,NaN,No Traffic Control,40.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,Male,Non-Traffic Fatality,Over Center Line,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,54.0,Female,Suspected Serious Injury,NaN,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1110778.239,753818.544,47.380701,-122.638040
41793,City Street,Yakima,Yakima,EB39835,CORNELL AVE,CORNELL AVE,1100.0,NaN,NaN,NaN,164.0,F,N,W PRASCH AVE,6/10/2021,2021,NaN,Suspected Serious Injury,1,0,1,0,0,0,0,1,0,0,4,0,0,NaN,Fence,One parked--one moving,Not at Intersection and Not Related,Clear,Dry,Straight & Level,Daylight,NaN,NaN,NaN,No,Past the Outside Shoulder of Primary Trafficway,Past the Outside Shoulder of Primary Trafficway,Passenger Car,CHEVROLET,IMPALA,Sedan,Other*,South,North,NaN,No Traffic Control,25.0,NaN,NaN,NaN,NaN,No Defects,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",FORD,F100,Pickup,"Legally Parked, Unoccupied",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Pickup,Panel Truck or Vanette under 10,000 lb",DODGE,Pickup,D-SERIES,"Legally Parked, Unoccupied",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Male,Non-Traffic Fatality,Apparently Ill,NaN,NaN,NaN,NaN,NaN,Lap & Shoulder Used,Not Ejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Reportable,1636722.940,456017.850,46.583848,-120.514691