In [1]:
import pandas as pd
import zipfile
from datetime import datetime
pd.set_option('display.max_columns', None)

In [7]:
for year in range(2006,2017):
    # EXTRACT DATA FROM ZIPFILES
    extract_path = f"{year}"
    zip_path = f"NewJersey{year}Accidents.zip"
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    zip_path = f"NewJersey{year}Vehicles.zip"
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    zip_path = f"NewJersey{year}Drivers.zip"
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    zip_path = f"NewJersey{year}Occupants.zip"
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    zip_path = f"NewJersey{year}Pedestrians.zip"
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    # Comb person-level CSVs to get all injury crash IDs
    injuries = set()
    deaths = set()
    with open(f"{year}/NewJersey{year}Pedestrians.txt", 'r') as file:
        for line in file:
            condition = line[35:37].strip()
            crash_id = line[:31].strip()
            if condition and int(condition) == 2:
                injuries.add(crash_id)
            if condition and int(condition) == 1:
                deaths.add(crash_id)
    
    with open(f"{year}/NewJersey{year}Occupants.txt", 'r') as file:
        for line in file:
            condition = line[38:40].strip()
            crash_id = line[:31].strip()
            if condition and int(condition) == 2:
                injuries.add(crash_id)
            if condition and int(condition) == 1:
                deaths.add(crash_id)
    # Create a set of crashes that contain a serious injury but no deaths
    injurycrashes = injuries - deaths

    with open(f"{year}/crash{year}.csv", "w") as f:
        f.write("id,dt,lat,lon,city,county,street_1,street_2,crash_type,death_count,severity\n")
        with open(f'{year}/NewJersey{year}Accidents.txt', 'r', encoding='latin-1') as file:
            for line in file:
                coords = line[353:370]
                crash_id = line[:31].strip()
                if coords != "       ,        ," and crash_id in injurycrashes:
                    total_killed = int(line[134:136])
                    total_injured = int(line[137:139])
                    severity = line[146:147]
                    date = line[70:80]
                    time = line[84:88].strip()
                    if not time:
                        time = "0000"
                    dt = datetime.strptime(date + " " + time, "%m/%d/%Y %H%M")
                    latitude = line[352:360]
                    longitude = line[361:369]
                    county = line[32:44].strip()
                    city = line[45:69].strip()
                    street_1 = line[160:210].strip()
                    street_2 = line[279:314].strip()
                    crash_type = line[154:156].strip()
                    f.write(f"{crash_id},{dt},{latitude},{longitude},{city},{county},{street_1},{street_2},{crash_type},{total_killed},{severity}\n")
    
    with open(f"{year}/pedestrian{year}.csv", "w") as f:
        f.write("id,bike,age,sex,condition\n")
        with open(f'{year}/NewJersey{year}Pedestrians.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    condition = line[35:37]
                    age = line[84:87].strip()
                    sex = line[88:89]
                    bike = line[197:198]
                    f.write(f"{crash_id},{bike},{age},{sex},{condition}\n")
    
    with open(f"{year}/occupant{year}.csv", "w") as f:
        f.write("id,vehicle_number,position,occupant_number,age,sex,condition\n")
        with open(f'{year}/NewJersey{year}Occupants.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    condition = line[38:40]
                    age = line[47:50].strip()
                    sex = line[51:52]
                    vehicle_number = line[32:34].strip()
                    occupant_number = line[35:37].strip()
                    position = line[41:43]
                    f.write(f"{crash_id},{vehicle_number},{position},{occupant_number},{age},{sex},{condition}\n")
    
    with open(f"{year}/vehicle{year}.csv", "w") as f:
        f.write("id,vehicle_number,year,make,model,hit_run\n")
        with open(f'{year}/NewJersey{year}Vehicles.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    vehicle_number = line[32:34].strip()
                    make = line[43:73].strip()
                    model = line[74:94].replace(",","").strip()
                    yr = line[99:103]
                    hit_run = line[239:240]
                    f.write(f"{crash_id},{vehicle_number},{yr},{make},{model},{hit_run}\n")
    
    with open(f"{year}/driver{year}.csv", "w") as f:
        f.write("id,vehicle_number,charge\n")
        with open(f'{year}/NewJersey{year}Drivers.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    vehicle_number = line[32:34].strip()
                    violation = line[95:125]
                    f.write(f"{crash_id},{vehicle_number},{violation}\n")

In [8]:
for year in range(2017,2019):
    # EXTRACT DATA FROM ZIPFILES
    # extract_path = f"{year}"
    # zip_path = f"NewJersey{year}Accidents.zip"
    # with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    #     zip_ref.extractall(extract_path)
    # zip_path = f"NewJersey{year}Vehicles.zip"
    # with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    #     zip_ref.extractall(extract_path)
    # zip_path = f"NewJersey{year}Drivers.zip"
    # with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    #     zip_ref.extractall(extract_path)
    # zip_path = f"NewJersey{year}Occupants.zip"
    # with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    #     zip_ref.extractall(extract_path)
    # zip_path = f"NewJersey{year}Pedestrians.zip"
    # with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    #     zip_ref.extractall(extract_path)
    # Comb person-level CSVs to get all injury crash IDs
    injuries = set()
    deaths = set()
    with open(f"{year}/NewJersey{year}Pedestrians.txt", 'r') as file:
        for line in file:
            condition = line[35:37].strip()
            crash_id = line[:31].strip()
            if condition and int(condition) == 2:
                injuries.add(crash_id)
            if condition and int(condition) == 1:
                deaths.add(crash_id)
    
    with open(f"{year}/NewJersey{year}Occupants.txt", 'r') as file:
        for line in file:
            condition = line[38:40].strip()
            crash_id = line[:31].strip()
            if condition and int(condition) == 2:
                injuries.add(crash_id)
            if condition and int(condition) == 1:
                deaths.add(crash_id)
    # Create a set of crashes that contain a serious injury but no deaths
    injurycrashes = injuries - deaths

    with open(f"{year}/crash{year}.csv", "w") as f:
        f.write("id,dt,lat,lon,city,county,street_1,street_2,crash_type,death_count,severity\n")
        with open(f'{year}/NewJersey{year}Accidents.txt', 'r', encoding='latin-1') as file:
            for line in file:
                coords = line[361:380]
                crash_id = line[:31].strip()
                if coords != "         ,         " and crash_id in injurycrashes:
                    total_killed = int(line[134:136])
                    severity = line[146:147]
                    date = line[70:80]
                    time = line[84:88].strip()
                    if not time:
                        time = "0000"
                    dt = datetime.strptime(date + " " + time, "%m/%d/%Y %H%M")
                    latitude = line[361:370]
                    longitude = line[371:380]
                    county = line[32:44].strip()
                    city = line[45:69].strip()
                    street_1 = line[160:210].strip()
                    street_2 = line[285:320].strip()
                    crash_type = line[154:156].strip()
                    f.write(f"{crash_id},{dt},{latitude},{longitude},{city},{county},{street_1},{street_2},{crash_type},{total_killed},{severity}\n")
    
    with open(f"{year}/pedestrian{year}.csv", "w") as f:
        f.write("id,bike,age,sex,condition\n")
        with open(f'{year}/NewJersey{year}Pedestrians.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    condition = line[35:37]
                    age = line[84:87].strip()
                    sex = line[88:89]
                    bike = line[387:388]
                    f.write(f"{crash_id},{bike},{age},{sex},{condition}\n")
    
    with open(f"{year}/occupant{year}.csv", "w") as f:
        f.write("id,vehicle_number,position,occupant_number,age,sex,condition\n")
        with open(f'{year}/NewJersey{year}Occupants.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    condition = line[38:40]
                    age = line[47:50].strip()
                    sex = line[51:52]
                    vehicle_number = line[32:34].strip()
                    occupant_number = line[35:37].strip()
                    position = line[41:43]
                    f.write(f"{crash_id},{vehicle_number},{position},{occupant_number},{age},{sex},{condition}\n")
    
    with open(f"{year}/vehicle{year}.csv", "w") as f:
        f.write("id,vehicle_number,year,make,model,hit_run\n")
        with open(f'{year}/NewJersey{year}Vehicles.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    vehicle_number = line[32:34].strip()
                    make = line[43:73].strip()
                    model = line[74:94].replace(",","").strip()
                    yr = line[99:103]
                    hit_run = line[271:272]
                    f.write(f"{crash_id},{vehicle_number},{yr},{make},{model},{hit_run}\n")
    
    with open(f"{year}/driver{year}.csv", "w") as f:
        f.write("id,vehicle_number,charge\n")
        with open(f'{year}/NewJersey{year}Drivers.txt', 'r', encoding='latin-1') as file:
            for line in file:
                crash_id = line[:31].strip()
                if crash_id in injurycrashes:
                    vehicle_number = line[32:34].strip()
                    violation = line[95:125]
                    f.write(f"{crash_id},{vehicle_number},{violation}\n")

In [2]:
new_crashes = pd.read_csv("crash.csv")

/var/folders/0r/74g1680s6rz9r8mbc5tx0_0c0000gn/T/ipykernel_90114/2303990507.py:1: DtypeWarning: Columns (0: Driverless Classification, 1: MCMX Number) have mixed types. Specify dtype option on import or set low_memory=False.
  new_crashes = pd.read_csv("crash.csv")

In [40]:
for x in new_crashes.index[1:]:
    crash_id = new_crashes['Crash ID'][x]
    dt = new_crashes['Date & Time of Crash'][x][:-4]
    print(new_crashes['Street Name'][x])
    print(new_crashes['Intersect Street Name'][x])
    print(new_crashes['Latitude'][x])
    print(new_crashes['Longitude'][x])
    print(new_crashes['County'][x])
    print(new_crashes['Municipality'][x])
    print(new_crashes['Crash Type'][x])
    print(dt)
    print("VEHICLE")
    print(new_crashes['Unit ID'][x])
    print(new_crashes['Unit Type'][x])
    print(new_crashes['Vehicle ID'][x])
    print(new_crashes['Vehicle Make'][x])
    # print(new_crashes['Vehicle Model'][x])
    print(new_crashes['Vehicle Type'][x])
    print(new_crashes['Hit and Run'][x])
    print(new_crashes['Citation Issued'][x])
    print("PERSON")
    print(new_crashes['Occupant ID'][x])
    print(new_crashes['Person ID'][x])
    print(new_crashes['Person Type'][x])
    print(new_crashes['Severity Rating (Person)'][x])
    print(new_crashes['Sex'][x])
    print(new_crashes['Age'][x])
    break

Rt 539 (Old York Road)
Herbert Road
40.21016886
-74.54761731
Monmouth
Upper Freehold Twp
Pedalcyclist
2023-08-04T20:17:00
VEHICLE
[551,552]
["Vehicle","Pedalcyclist"]
541
FORD
Pick Up
No
["No","No"]
PERSON
[null,680]
[1495,1497]
["Driver","Pedalcyclist"]
["No Apparent Injury (O)","Suspected Serious Injury (A)"]
["Male","Male"]
[27,50]

In [101]:
new_crashes[['Unit ID', 'Unit Type', 'Vehicle ID','Vehicle Type','Person ID', 'Person Type','Hit and Run','Citation Issued','Sex',"Age",'Severity Rating (Person)']][2028:2040]

,Unit ID,Unit Type,Vehicle ID,Vehicle Type,Person ID,Person Type,Hit and Run,Citation Issued,Sex,Age,Severity Rating (Person)
2028,"[10566486,[10566487,10566487,10566487]]","[""Vehicle"",""Vehicle""]","[10404127,10404128]","[""Car/Station Wagon/Minivan"",""Sport Utility Ve...","[26049719,[26049721,26049722,26049723]]","[""Driver"",[""Driver"",""Passenger"",""Passenger""]]","[""No"",""No""]","[""No"",[""Yes"",""No"",""No""]]","[""Female"",[""Male"",""Male""]]","[[21,20,0],35]","[[""Suspected Minor Injury (B)"",""Suspected Mino..."
2029,"[10566611,10566612]","[""Vehicle"",""Pedestrian""]",10404250,Car/Station Wagon/Minivan,"[26050003,26050004]","[""Driver"",""Pedestrian""]","[""No"",""No""]","[""No"",""Yes""]","[""Male"",""Male""]","[25,52]","[""No Apparent Injury (O)"",""Suspected Serious I..."
2030,"[10567038,10567039]","[""Vehicle"",""Vehicle""]","[10404669,10404670]","[""Car/Station Wagon/Minivan"",""Sport Utility Ve...","[26050957,26050959]","[""Driver"",""Driver""]","[""No"",""No""]","[""No"",""No""]","[""Female"",""Male""]","[38,44]","[""Suspected Serious Injury (A)"",""Suspected Ser..."
2031,"[[10567154,10567154],10567155]","[""Vehicle"",""Vehicle""]","[10404785,10404786]","[""Car/Station Wagon/Minivan"",""Sport Utility Ve...","[[26051214,26051215],26051217]","[""Driver"",[""Driver"",""Passenger""]]","[""Yes"",""No""]","[""No"",[""No"",""No""]]","[""Female"",[""Female"",""Female""]]","[40,[61,10]]","[""No Apparent Injury (O)"",[""Suspected Serious ..."
2032,10567181,Vehicle,10404812,Car/Station Wagon/Minivan,26051273,Driver,No,No,Male,22,Suspected Serious Injury (A)
2033,"[[10567388,10567388,10567388],10567389]","[""Vehicle"",""Pedestrian""]",10405019,Sport Utility Vehicle,"[[26051749,26051750,26051751],26051752]","[[""Driver"",""Passenger"",""Passenger""],""Pedestrian""]","[""Yes"",""No""]","[""No"",[""Yes"",""No"",""No""]]","[""Male"",[""Male"",""Female"",""Female""]]","[[23,29,31],61]","[""Fatal Injury (K)"",[""No Apparent Injury (O)"",..."
2034,"[10567578,[10567579,10567579]]","[""Vehicle"",""Vehicle""]","[10405208,10405209]","[""Motorcycle"",""Sport Utility Vehicle""]","[26052219,[26052221,26052222]]","[""Driver"",[""Driver"",""Passenger""]]","[""No"",""No""]","[""No"",[""No"",""No""]]","[[""Female"",""Male""],""Male""]","[34,[76,86]]","[""Fatal Injury (K)"",[""No Apparent Injury (O)"",..."
2035,"[10567585,10567586]","[""Vehicle"",""Pedestrian""]",10405215,Car/Station Wagon/Minivan,"[26052234,26052235]","[""Driver"",""Pedestrian""]","[""No"",""No""]","[""No"",""No""]","[""Male"",""Male""]","[38,47]","[""Fatal Injury (K)"",""No Apparent Injury (O)""]"
2036,"[[10567775,10567775],10567776,10567777]","[""Vehicle"",""Vehicle"",""Pedestrian""]","[10405404,10405405]","[""Car/Station Wagon/Minivan"",""Car/Station Wago...","[[26052680,26052681],26052683,26052684]","[""Driver"",[""Driver"",""Passenger""],""Pedestrian""]","[""No"",""No"",""No""]","[""No"",""No"",[""Yes"",""No""]]","[null,""Male"",[""Male"",""Female""]]","[0,32,[60,41]]","[""No Apparent Injury (O)"",[""No Apparent Injury..."
2037,"[[10567826,10567826,10567826],10567827]","[""Vehicle"",""Vehicle""]","[10405452,10405453]","[""Car/Station Wagon/Minivan"",""Car/Station Wago...","[[26052794,26052795,26052796],26052798]","[""Driver"",[""Driver"",""Passenger"",""Passenger""]]","[""No"",""No""]","[""No"",[""Yes"",""No"",""No""]]","[""Female"",[""Male"",""Male""]]","[36,[61,64,63]]","[[""No Apparent Injury (O)"",""Possible Injury (C..."
2038,"[10568169,10568170]","[""Vehicle"",""Pedalcyclist""]",10405790,Car/Station Wagon/Minivan,"[26053575,26053576]","[""Driver"",""Pedalcyclist""]","[""No"",""No""]","[""No"",""Yes""]","[""Female"",""Male""]","[19,45]","[""No Apparent Injury (O)"",""Suspected Serious I..."
2039,"[10568407,10568408]","[""Vehicle"",""Vehicle""]","[10406021,10406022]","[""Car/Station Wagon/Minivan"",""Sport Utility Ve...","[26054116,26054118]","[""Driver"",""Driver""]","[""No"",""No""]","[""No"",""Yes""]","[""Female"",""Male""]","[19,57]","[""Suspected Serious Injury (A)"",""Suspected Ser..."

In [92]:
for x in new_crashes:
    num_person_ids =

SyntaxError: cannot assign to attribute here. Maybe you meant '==' instead of '='? (1426869739.py, line 1)

In [57]:
new_crashes['Unit ID'][2].replace("[","").replace("]","").split(",")

['569', '569', '569', '569', '570', '570', '570', '570', '570']

In [58]:
from collections import Counter

In [59]:
Counter(new_crashes['Unit ID'][2].replace("[","").replace("]","").split(","))

Counter({'570': 5, '569': 4})

In [61]:
dict(Counter(new_crashes['Unit ID'][2].replace("[","").replace("]","").split(",")))

{'569': 4, '570': 5}

In [69]:
dict(Counter(new_crashes['Unit ID'][0].replace("[","").replace("]","").split(",")))

{'519': 1}

In [70]:
for z in dict(Counter(new_crashes['Unit ID'][0].replace("[","").replace("]","").split(","))):
    print(z)

519

In [16]:
ROW 71 is all fucked up
ROW 298 is all fucked up
ROW 443 is all fucked up
ROW 447 is all fucked up
ROW 587 is all fucked up
ROW 706 is all fucked up
ROW 770 is all fucked up
ROW 863 is all fucked up
ROW 887 is all fucked up
ROW 888 is all fucked up
ROW 1245 is all fucked up
ROW 1329 is all fucked up
ROW 1374 is all fucked up
ROW 1472 is all fucked up
ROW 1514 is all fucked up
ROW 1542 is all fucked up
ROW 1575 is all fucked up
ROW 1694 is all fucked up
ROW 1754 is all fucked up
ROW 1763 is all fucked up
ROW 1830 is all fucked up
ROW 1891 is all fucked up
ROW 1910 is all fucked up
ROW 1922 is all fucked up
ROW 1929 is all fucked up
ROW 1942 is all fucked up
ROW 2028 is all fucked up
ROW 2037 is all fucked up
ROW 2110 is all fucked up
ROW 2223 is all fucked up
ROW 2229 is all fucked up
ROW 2238 is all fucked up
ROW 2295 is all fucked up
ROW 2307 is all fucked up
ROW 2316 is all fucked up
ROW 2352 is all fucked up
ROW 2362 is all fucked up
ROW 2433 is all fucked up
ROW 2435 is all fucked up
ROW 2438 is all fucked up
ROW 2458 is all fucked up
ROW 2579 is all fucked up
ROW 2605 is all fucked up
ROW 2662 is all fucked up
ROW 2674 is all fucked up
ROW 2722 is all fucked up
ROW 2831 is all fucked up
ROW 2894 is all fucked up
ROW 2924 is all fucked up
ROW 3001 is all fucked up
ROW 3059 is all fucked up
ROW 3078 is all fucked up
ROW 3101 is all fucked up
ROW 3146 is all fucked up
ROW 3150 is all fucked up
ROW 3170 is all fucked up
ROW 3198 is all fucked up
ROW 3215 is all fucked up
ROW 3247 is all fucked up
ROW 3344 is all fucked up
ROW 3391 is all fucked up
ROW 3456 is all fucked up
ROW 3494 is all fucked up
ROW 3577 is all fucked up
ROW 3751 is all fucked up
ROW 3788 is all fucked up
ROW 3791 is all fucked up
ROW 3800 is all fucked up
ROW 3844 is all fucked up
ROW 4011 is all fucked up
ROW 4024 is all fucked up
ROW 4035 is all fucked up
ROW 4096 is all fucked up
ROW 4100 is all fucked up
ROW 4122 is all fucked up
ROW 4271 is all fucked up
ROW 4396 is all fucked up
ROW 4415 is all fucked up
ROW 4417 is all fucked up
ROW 4481 is all fucked up
ROW 4622 is all fucked up
ROW 4837 is all fucked up
ROW 4864 is all fucked up
ROW 4949 is all fucked up
ROW 5031 is all fucked up
ROW 5059 is all fucked up
ROW 5197 is all fucked up
ROW 5376 is all fucked up
ROW 5396 is all fucked up
ROW 5503 is all fucked up
ROW 5546 is all fucked up
ROW 5765 is all fucked up
ROW 5786 is all fucked up
ROW 5815 is all fucked up
ROW 6117 is all fucked up
ROW 6213 is all fucked up
ROW 6226 is all fucked up
ROW 6234 is all fucked up
ROW 6497 is all fucked up
ROW 6567 is all fucked up
ROW 6576 is all fucked up
ROW 6584 is all fucked up
ROW 6729 is all fucked up
ROW 6731 is all fucked up
ROW 6847 is all fucked up
ROW 6917 is all fucked up
ROW 7004 is all fucked up
ROW 7099 is all fucked up
ROW 7124 is all fucked up
ROW 7147 is all fucked up
ROW 7149 is all fucked up
ROW 7152 is all fucked up
ROW 7200 is all fucked up
ROW 7206 is all fucked up
ROW 7244 is all fucked up
ROW 7362 is all fucked up
ROW 7401 is all fucked up
ROW 7414 is all fucked up
ROW 7469 is all fucked up
ROW 7559 is all fucked up
ROW 7563 is all fucked up
ROW 7595 is all fucked up
ROW 7704 is all fucked up
ROW 7824 is all fucked up
ROW 7949 is all fucked up
ROW 8018 is all fucked up
ROW 8083 is all fucked up
ROW 8104 is all fucked up
ROW 8182 is all fucked up
ROW 8191 is all fucked up
ROW 8222 is all fucked up
ROW 8278 is all fucked up
ROW 8318 is all fucked up
ROW 8379 is all fucked up
ROW 8381 is all fucked up
ROW 8388 is all fucked up
ROW 8930 is all fucked up
ROW 9001 is all fucked up
ROW 9109 is all fucked up
ROW 9288 is all fucked up
ROW 9339 is all fucked up
ROW 9416 is all fucked up
ROW 9803 is all fucked up
ROW 9872 is all fucked up
ROW 10183 is all fucked up
ROW 10249 is all fucked up
ROW 10292 is all fucked up
ROW 10417 is all fucked up
ROW 10418 is all fucked up
ROW 10490 is all fucked up
ROW 10550 is all fucked up
ROW 10730 is all fucked up
ROW 10810 is all fucked up
ROW 10817 is all fucked up
ROW 10838 is all fucked up
ROW 10859 is all fucked up
ROW 10887 is all fucked up
ROW 10930 is all fucked up
ROW 10940 is all fucked up
ROW 10958 is all fucked up
ROW 10962 is all fucked up
ROW 11027 is all fucked up
ROW 11182 is all fucked up
ROW 11322 is all fucked up
ROW 11409 is all fucked up
ROW 11421 is all fucked up
ROW 11628 is all fucked up
ROW 11729 is all fucked up
ROW 11779 is all fucked up
ROW 11969 is all fucked up
ROW 12090 is all fucked up
ROW 12177 is all fucked up
ROW 12209 is all fucked up
ROW 12221 is all fucked up
ROW 12284 is all fucked up
ROW 12629 is all fucked up
ROW 12826 is all fucked up
ROW 12830 is all fucked up
ROW 12841 is all fucked up
ROW 13000 is all fucked up
ROW 13072 is all fucked up
ROW 13172 is all fucked up
ROW 13204 is all fucked up
ROW 13240 is all fucked up
ROW 13299 is all fucked up
ROW 13304 is all fucked up
ROW 13359 is all fucked up
ROW 13445 is all fucked up
ROW 13468 is all fucked up
ROW 13533 is all fucked up
ROW 13774 is all fucked up
ROW 13775 is all fucked up
ROW 13819 is all fucked up
ROW 13878 is all fucked up
ROW 13886 is all fucked up
ROW 14061 is all fucked up
ROW 14243 is all fucked up
ROW 14376 is all fucked up
ROW 14488 is all fucked up
ROW 14621 is all fucked up
ROW 14646 is all fucked up
ROW 14717 is all fucked up
ROW 14724 is all fucked up
ROW 14727 is all fucked up
ROW 14765 is all fucked up
ROW 14881 is all fucked up
ROW 14896 is all fucked up
ROW 14900 is all fucked up
ROW 14928 is all fucked up
ROW 14957 is all fucked up
ROW 14966 is all fucked up
ROW 14981 is all fucked up
ROW 15008 is all fucked up
ROW 15011 is all fucked up
ROW 15076 is all fucked up
ROW 15121 is all fucked up
ROW 15156 is all fucked up
ROW 15161 is all fucked up
ROW 15195 is all fucked up
ROW 15342 is all fucked up
ROW 15815 is all fucked up
ROW 15999 is all fucked up
ROW 16009 is all fucked up
ROW 16066 is all fucked up
ROW 16181 is all fucked up
ROW 16406 is all fucked up
ROW 16445 is all fucked up
ROW 16879 is all fucked up
ROW 16924 is all fucked up
ROW 17049 is all fucked up
ROW 17256 is all fucked up
ROW 17283 is all fucked up
ROW 17305 is all fucked up
ROW 17308 is all fucked up
ROW 17320 is all fucked up
ROW 17364 is all fucked up
ROW 17409 is all fucked up
ROW 17414 is all fucked up
ROW 17432 is all fucked up
ROW 17553 is all fucked up
ROW 17643 is all fucked up
ROW 17744 is all fucked up
ROW 17895 is all fucked up
ROW 17920 is all fucked up
ROW 17923 is all fucked up
ROW 17930 is all fucked up
ROW 17931 is all fucked up
ROW 17935 is all fucked up
ROW 17940 is all fucked up
ROW 17944 is all fucked up
ROW 17947 is all fucked up
ROW 18078 is all fucked up
ROW 18166 is all fucked up
ROW 18236 is all fucked up
ROW 18365 is all fucked up
ROW 18590 is all fucked up
ROW 18690 is all fucked up
ROW 18708 is all fucked up
ROW 18771 is all fucked up
ROW 18774 is all fucked up
ROW 18783 is all fucked up
ROW 19007 is all fucked up
ROW 19097 is all fucked up
ROW 19291 is all fucked up
ROW 19377 is all fucked up
ROW 19406 is all fucked up
ROW 19462 is all fucked up
ROW 19666 is all fucked up
ROW 19677 is all fucked up
ROW 19758 is all fucked up
ROW 20008 is all fucked up
ROW 20053 is all fucked up
ROW 20055 is all fucked up
ROW 20620 is all fucked up
ROW 20910 is all fucked up
ROW 20951 is all fucked up
ROW 21034 is all fucked up
ROW 21059 is all fucked up
ROW 21324 is all fucked up
ROW 21344 is all fucked up
ROW 21402 is all fucked up
ROW 21664 is all fucked up
ROW 21719 is all fucked up
ROW 21769 is all fucked up
ROW 21811 is all fucked up
ROW 22111 is all fucked up
ROW 22198 is all fucked up
ROW 22402 is all fucked up
ROW 22493 is all fucked up
ROW 22570 is all fucked up
ROW 23057 is all fucked up
ROW 23077 is all fucked up
ROW 23389 is all fucked up
ROW 23434 is all fucked up
ROW 23565 is all fucked up
ROW 23675 is all fucked up
ROW 23754 is all fucked up
ROW 23812 is all fucked up
ROW 23816 is all fucked up
ROW 24027 is all fucked up
ROW 24077 is all fucked up
ROW 24127 is all fucked up
ROW 24136 is all fucked up
ROW 24147 is all fucked up
ROW 24205 is all fucked up
ROW 24247 is all fucked up
ROW 24331 is all fucked up
ROW 24333 is all fucked up

,Age,Age of Infant (Months),Airbag,Alcohol Test Given,Alcohol Test ID,Alcohol Test Result,Alcohol Test Result Pending,Alcohol Test Type,Cargo Body Type,Carrier City,Carrier State,Carrier Zip,Citation Issued,Commercial Vehicle ID,Countermeasure: No Turn On Red,Direction of Travel,Distracted Driving,Driver Age,Driver Age Group,Driver Is Owner,Driverless Classification,Driver's License Class,Driver's License Endorsements,Driver's License ID,Driver's License Restrictions,Driver's License State,Ejection,Events,Extent of Damage,Eye Color,Factors,Functional Class,Hazmat Status,Hit and Run,Hospital,Initial Impact,Injury Location,Injury Status,Injury Type,Insurance,MCMX Number,Most Harmful Event of Unit,Occupant ID,Original Unit Number,Overweight Permit,Person ID,Person Type,Physical Condition ID,Physical Statuses,Placard,Plate State,Position in Vehicle,Pre-Crash Action,Railcar Involved,Refused Treatment,Removed By,Removed To,Response to Emergency,Roadway or Lane Departure,Safety Equipment Available,Safety Equipment Used,Segment ID,Severity Rating (Person),Sex,Special Function,State,State.1,Total Bicyclists,Total Bicyclists Killed,Total Drivers,Total Incapacitated,Total Injured Bicyclists (Not Killed),Total Occupants,Traffic Control,Unit ID,Unit Type,Unrestrained Occupant Involved,Unsafe Speed,Urban or Rural,USDOT Number,Vehicle Color,Vehicle ID,Vehicle Make,Vehicle Model,Vehicle Type,Vehicle Use,Weight Rating,Zip Code,Agency ORI,Alcohol Involved,Animal Involved,At Intersection,Bicyclist Involved,Case Number,Countermeasure: Backplate,County,Crash Fatality Count,Crash ID,Crash Type,Damage to Property,Date & Time of Crash,Date of Crash,Day of Week,Department ORI,State Police Station,Direction From Intersection,Distance From Intersection (Ft),Document Locator #,Drowsy Driver Involved,Drugged Driver Involved,Fatal Crash Indicator,First Harmful Event,Geopoint,Geopoint (Calculated),Hazmat Involved,Head-On Collision,Highest Injury Severity Rating,Intersect Route Number,Intersect SRI,Intersect Street Name,Intersection Crash Rate Contribution,Intersection Major AADT,Intersection Minor AADT,Intersection Speed Limit,Intersection TEV,Is Private Property,Latitude,Light Condition,Longitude,Milepost,Motorcycle Involved,Municipality,NJDOT Summary,Older Driver Involved,Pedestrian Involved,Pedestrian or Bicyclist Involved,Ramp,Ramp Direction,Ramp Route Number,Ramp SRI,Ramp Street Name,Road Character - Grade,Road Horizontal Alignment,Road Median,Road Surface Type,Road System,Roadway Direction,Route Number,Route Suffix,Run Off Road,Segment AADT,Segment Crash Rate Contribution,Segment Per Mile Contribution,SHSP Emphasis Areas,Single Vehicle Crash,Speed Limit,SRI,Street Name,Surface Condition,Third-Party Document Locator #,Time of Crash,Total Injured,Total Injured Pedestrians,Total Killed,Total Pedestrians Killed,Total Vehicles,Traffic Control Zone,Unable to Geocode Crash,Weather Condition,Window Crash Rate Contribution,Work Zone Related,Year,Young Driver Involved
0,55,NaN,Not Applicable,No,529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,North,No,55,50-59,Yes,NaN,Auto,NaN,519,Corrective Lenses Required,New Jersey,Not Ejected,"[""Overturn/Rollover"",""Not Applicable"",""Not App...",Minor,Brown,"[""Other Roadway Factors"",""None""]",Local Road,NaN,No,UMDNJ - University Hospital,Left Side - Near Front,Knee/Lower Leg/Foot,Suspected Serious Injury (A),Fracture/Dislocation,NaN,NaN,Overturn/Rollover,642,1,NaN,1410,Driver,629,"[""Apparently Normal"",""Not Applicable""]",NaN,Pennsylvania,Driver,Making Left Turn,No,No,Police,NaN,No,No,Helmet,Helmet,32469.0,Suspected Serious Injury (A),Male,Not Applicable,New Jersey,New Jersey,NaN,NaN,1.0,1.0,NaN,1.0,Not Applicable,519,Vehicle,No,No,Urban,NaN,Black,509,HARLEY DAVIDSON,NaN,Motorcycle,Personal,NaN,07036,NJ0202100,No,No,Yes,No,23-002594,No,Union,0,283,Overturned,Yes,2023-12-02T13:45:00.000,2023-12-02,Saturday,NJ0202100,NaN,NaN,0.0,20212023-23-002594,No,No,N,Overturn/Rollover,"{""lon"":-74.28565921,""lat"":40.63724701}","{""lon"":-74.28564943,""lat"":40.63723935}",No,No,Suspected Serious Injury (A),NaN,20211001__,WAVECREST AVE,0.000067,7421.0,7421.0,25.0,14842.0,No,40.637247,Daylight,-74.285659,0.23,Yes,Winfield Twp,"[""Motorcycle Involved"",""Injury Crashes"",""Total...",No,No,No,NaN,NaN,NaN,NaN,NaN,Down Hill,Curved Left,NaN,Blacktop,Municipal,NaN,NaN,NaN,No,NaN,NaN,4.347269,"[""Motorcycle Involved"",""At Intersection""]",Yes,25.0,20211006__,ATLANTIC DR,Dry,NaN,13:45:00,1,0,0,0,1,NaN,No,Clear,NaN,No,2023,No
1,"[27,50]","[null,null]","[null,""Not Deployed""]","[""No"",""No""]","[559,560]","[null,null]","[null,null]","[null,null]",NaN,NaN,NaN,NaN,"[""No"",""No""]",NaN,"[""No"",""No""]","[""West"",""North""]","[""Yes"",""No""]","[null,27]",20-29,Yes,NaN,"[null,""Auto""]","[null,null]","[null,549]","[null,null]","[null,""New Jersey""]","[null,""Not Ejected""]","[""Pedacyclist"",""Not Applicable"",""Not Applicabl...",NaN,"[""Brown"",""Brown""]","[""Driver Inattention"",""Not Applicable"",""None"",...",Major Collector,NaN,No,"[null,""CentraState Healthcare System""]",None Visible,"[null,""Hip/Upper Leg""]","[""No Apparent Injury (O)"",""Suspected Serious I...","[null,""Bleeding""]",NaN,NaN,"[""Pedalcyclist"",""MV in Transport""]","[null,680]","[""1"",""B1""]",NaN,"[1495,1497]","[""Driver"",""Pedalcyclist""]","[665,666]","[[""Apparently Normal"",""Not Applicable""],[""Appa...",NaN,New Jersey,"[null,""Driver""]","[""Making Right Turn ( not turn on red)"",""Going...","[""No"",""No""]","[null,""No""]",Owner,NaN,No,"[""No"",""No""]","[""Helmet"",""Lap Belt & Harness""]","[""Helmet"",""Lap Belt & Harness""]",13400.0,"[""No Apparent Injury (O)"",""Suspected Serious I...","[""Male"",""Male""]",Not Applicable,New Jersey,"[""New Jersey"",""New Jersey""]",1.0,NaN,1.0,1.0,1.0,1.0,"[""Stop Sign"",""Lane Markings""]","[551,552]","[""Vehicle"",""Pedalcyclist""]","[""No"",""No""]","[""No"",""No""]",Rural,NaN,Red,541,FORD,"[[null,null],[null,null]]",Pick Up,Personal,NaN,"[""08520"",""08520""]",NJNSP0000,No,No,Yes,Yes,C060202300289C,No,Monmouth,0,300,Pedalcyclist,Yes,2023-08-04T20:17:00.000,2023-08-04,Friday,NJNSP0000,Hamilton,East,0.0,13512023-C060202300289C,No,No,N,Pedacyclist,"{""lon"":-74.54761731,""lat"":40.21016886}","{""lon"":-74.54762946,""lat"":40.21030151}",No,No,Suspected Serious Injury (A),NaN,13511021__,Herbert Road,0.000093,5397.0,5397.0,50.0,10794.0,No,40.210169,Dark (no street lights),-74.547617,47.45,No,Upper Freehold Twp,"[""Distracted Driving Related"",""Bicyclist Invol...",No,No,Yes,NaN,NaN,NaN,NaN,NaN,Level,Straight,NaN,Blacktop,County,North,539.0,NaN,No,5397.0,0.000061,0.328947,"[""Distracted Driving Related"",""Bicyclist Invol...",Yes,50.0,00000539__,Rt 539 (Old York Road),Dry,NaN,20:17:00,1,0,0,0,1,NaN,No,Clear,0.000185,No,2023,No
2,"[[8,33,33,19,6],[39,33,15,15]]","[null,null]","[[""Combination"",""Combination"",""Combination"",""C...","[""No"",""No""]","[577,578]","[null,null]","[null,null]","[null,null]",NaN,NaN,NaN,NaN,"[""No"",""No""]",NaN,"[""No"",""No""]","[""West"",""East""]","[""No"",""No""]","[33,39]","[""30-39"",""30-39""]","[""No"",""Yes""]",NaN,"[""Auto"",""Auto""]","[null,null]","[566,567]","[null,null]","[""New Jersey"",""New Jersey""]","[[""Not Applicable"",""Not Applicable"",""Not Appli...","[""MV in Transport"",""Not Applicable"",""Not Appli...","[""Disabling"",""Disabling""]","[""Brown"",""Brown""]","[""Improper Passing"",""Not Applicable"",""None"",""N...",Major Collector,NaN,"[""No"",""No""]","[[""Unknown"",""Unknown"",""Unknown"",""Unknown""],[""U...","[""Front End"",""Front End""]","[[""Knee/Lower Leg/Foot"",""Entire Body"",""Chest"",...","[[""Suspected Minor Injury (B)"",""Possible Injur...","[[""Complaint of Pain"",""Internal"",""Complaint of...",NaN,NaN,"[""MV in Transport"",""MV in Transport""]","[[698,699,700,701],[706,702,703,704,705]]","[""1"",""2""]",NaN,"[[1541,1542,1543,1544],[1549,1545,1546,1547,15...","[[""Driver"",""Passenger"",""Passenger"",""Passenger""...","[[684,685,686,687],[692,688,689,690,691]]","[[""Apparently Normal"",""Not Applicable""],[""Appa...","[""None"",""None""]","[""New Jersey"",""New Jersey""]","[[""Driver"",""Front Seat - Right Side"",""Rear Sea...","[""Going Straight Ahead"",""Going Straight Ahead""]","[""No"",""No""]","[[""No"",""No"",""No"",""No""],[""No"",""No"",""No"",""No"",""N...","[""Police"",""Police""]","[""1520 E State St"",""1520 E State St""]","[""No"",""No""]","[""No"",""No""]","[[""Lap Belt & Harness"",""Lap Belt & Harness"",""L...","[[""Unknown"",""Unknown"",""Lap Belt & Harness"",""Un...",7001.0,"[[""Suspected Minor Injury (B)"",""Possible Injur...","[[""Male"",""Female"",""Male"",""Female""],[""Male"",""Fe...","[""Not Applicable"",""Not Applicable""]",New Jersey,"[[""New Jersey"",""New Jersey"",""New Jersey"",""New ...",NaN,NaN,2.0,2.0,NaN,9.0,"[""Lane Markings"",""Lane Markings""]","[[569,569,569,569],[570,570,570,570,570]]","[""Vehicle"",""Vehicle""]","[[""No"",""No"",""No"",""No""],[""No"",""No"",""No"",""No"",""N...","[""No"",""No""]",Urban,"[""None"",""None""]","[""Black"",""Gray""]","[558,559]","[""CHEVROLET"",""DODGE""]","[[null,null],[null,null]]","[""Car/Station Wagon/Minivan"",""Car/Station Wago...","[""Personal"",""Personal""]",NaN,"[[""08103"",""08110"",""08110"",""08104"",""08103""],[""0...",NJ0040800,No,No,No,No,2309140474,No,Camden,0,310,"Opposite Direction (Head On, Angular)",Yes,2023-09-14T17:00:00.000,2023-09-14,Thursday,NJ0040800,NaN,West,285.0,04082023-2309140474,No,No,N,MV in Transport,"{""lon"":-75.10423093,""lat"":39.95174118}","{""lon"":-75.10426178,""lat"":39.95162917}",No,Yes,Suspected Serious Injury (A),NaN,04081282__,N 17TH ST,NaN,NaN,NaN,NaN,NaN,No,39.951741,Daylight,-75.104231,0.11,No,Camden City,"[""Injury Crashes"",""Total Crashes""]",No,No,No,NaN,NaN,NaN,NaN,NaN,Level,Straight,Painted Median,Blacktop,Municipal,North,NaN,NaN,No,2669.0,0.000487,1.298652,NaN,No,25.0,04081617__,HARRISON AVE,Dry,NaN,17:00:00,9,0,0,0,2,NaN,No,Clear,0.000375,No,2023,No
3,"[70,75]","[null,null]","[null,""Not Deployed""]","[""No"",""No""]","[589,590]","[null,null]","[null,null]","[null,null]",NaN,NaN,NaN,NaN,"[""No"",""Yes""]",NaN,"[""No"",""No""]","[""South"",""West""]","[""Yes"",""No""]","[null,70]",70-74,No,NaN,"[null,""Auto""]","[null,null]","[null,578]","[null,null]","[null,""New Jersey""]","[null,""Not Ejected""]","[""Pedestrian"",""Not Applicable"",""Not Applicable...",Moderate/Functional,"[""Brown"",""Brown""]","[""Driver Inattention"",""None"",""Crossing Where P...",Major Collector,NaN,Yes,"[null,""Hackensack University Medical Center""]",Front End,"[null,""Abdomen/Pelvis""]","[""Fatal Injury (K)"",""No Apparent Injury (O)""]","[null,""Bleeding""]",NaN,NaN,"[""Pedestrian"",""MV in Transport""]","[null,727]","[""1"",""P1""]",NaN,"[1589,1590]","[""Driver"",""Pedestrian""]","[711,712]","[[""Apparently Normal"",""Not Applicable""],[""Appa...",NaN,New Jersey,"[null,""Driver""]","[""Going Straight Ahead"",""Crossing/Jaywalking""]","[""No"",""No""]","[null,""No""]",Driver,NaN,No,"[""No"",""No""]","[""Lap Belt & Harness"",""Not Applicable""]","[""Lap Belt & Harness"",""Not Applicable""]",23313.0,"[""Fatal Injury (K)"",""No Apparent Injury (O)""]","[""Male"",""Male""]",Not Applicable,New Jersey,"[""New Jersey"",""New Jersey""]",NaN,NaN,1.0,NaN,NaN,1.0,"[""No Control Present"",""Traffic Signal""]","[583,584]","[""Vehicle"",""Pedestrian""]","[""No"",""No""]","[""No"",""No""]",Urban,NaN,Tan,572,LEXUS,"[[null,null],[null,null]]",Sport Utility Vehicle,Personal,NaN,"[""07024"",""07522""]",NJ0023700,No,No,No,No,37-23-011262,No,Bergen,1,316,Pedestrian,Yes,2023-09-13T04:46:00.000,2023-09-13,Wednesday,NJ0023700,NaN,West,184.0,02622023-37-23-011262,No,No,Y,Pedestrian,"{""lon"":-74.05905749,""lat"":40.86133991}","{""lon"":-74.05908161,""lat"":40.86124429}",No,No,Fatal Injury (K),46.0,00000046__,US 46,0.000020,43768.0,5650.0,50.0,49418.0,No,40.861340,"Dark (street lights on, spot)",-74.059057,1.73,No,Teterboro Boro,"[""Distracted Driving Related"",""Older Driver In...",Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,Level,Straight,NaN,Blacktop,Municipal,North,NaN,NaN,No,13885.0,0.000107,1.492472,"[""Distracted Driving Related"",""Older Driver In...",Yes,25.0,02371100__,INDUSTRIAL AVE,Wet,NaN,04:46:00,0,0,1,1,1,NaN,No,Rain,0.000072,No,2023,No
4,"[40,47]","[null,null]","[null,""Combination""]","[""No"",""Refused""]","[1081,1082]","[null,null]","[null,null]","[null,null]",NaN,NaN,NaN,NaN,"[""No"",""Yes""]",NaN,"[""No"",""No""]","[""West"",""South""]","[""No"",""No""]","[40,47]","[""40-49"",""40-49""]",NaN,NaN,"[""Auto"",""Auto""]","[null,""Tank Vehicle""]","[1058,1059]","[null,""Except Class A&B Passenger Vehicles""]","[""New Jersey"",""New York""]","[""Not Ejected"",""Not Ejected""]","[""MV in Transport"",""MV in Transport"",""Bridge R...","[""Disabling"",""Disabling""]","[""Black"",""Brown""]","[""Failed to Obey Traffic Signal"",""Unsafe Speed...",Principal Arterial - Other,NaN,"[""Yes"",""No""]","[null,""Atlantic Health System - Overlook Medic...","[""Front End"",""Left Side - Center""]","[null,""Knee/Lower Leg/Foot""]","[""Possible Injury (C)"",""Suspected Serious Inju...","[""Contusion/Bruise/Abrasion"",""Unknown""]",NaN,NaN,"[""MV in Transport"",""MV in Transport""]","[1307,1308]","[""1"",""2""]",NaN,"[2883,2884]","[""Driver"",""Driver""]","[1267,1268]","[""Alcohol & Drug Medication Use"",""Apparently N...","[""None"",""None""]","[""New Jersey"",""New York""]","[""Driver"",""Driver""]","[""Going Straight Ahead"",""Going Straight Ahead""]","[""No"",""No""]","[null,null]","[""Police"",""Police""]","[""Seton Towing - 31 Newark Way; Maple"",""Seton ...","[""No"",""No""]","[""No"",""No""]","[""Lap Belt & Harness"",""Unknown""]","[""Lap Belt & Harness"",""Unknown""]",66874.0,"[""Possible Injury (C)"",""Suspected Serious Inju...","[""Female"",""Male""]","[""Not Applicable"",""Work Equipment""]",New Jersey,"[""New Jersey"",""New York""]",NaN,NaN,2.0,1.0,NaN,2.0,"[""Traffic Signal"",""Traffic Signal""]","[1075,1076]","[""Vehicle"",""Vehicle""]","[""No"",""No""]","[""Yes"",""No""]",Urban,"[""None"",""None""]",White,"[1053,1054]","[""FOR"",""HONDA""]","[[null,null],[""CARAVELLE"",""TRANSPORTER""]]","[""Cargo Van (10K lbs or less)"",""Sport Utility ...","[""Business/Commerce"",""Personal""]",NaN,"[""07105-3026"",""10035""]",NJ0071200,Yes,No,No,No,I-2023-018905,No,Essex,0,572,Right Angle,No,2023-09-16T09:00:00.000,2023-09-16,Saturday,NJ0071200,NaN,NaN,NaN,07122023-I-2023-018905,No,No,N,MV in Transport,"{""lon"":-74.34576973,""lat"":40.72738013}","{""lon"":-74.3458443,""lat"":40.72742655}",No,No,Suspected Serious Injury (A),NaN,20181002__,HOBART AVE,0.000042,11868.0,11868.0,0.0,23736.0,No,40.727380,Daylight,-74.345770,8.96,No,Millburn Twp,"[""Alcohol Involved"",""Unsafe Speed Related"",""In...",No,No,No,NaN,NaN,NaN,NaN,NaN,Up Hill,Straight,NaN,Blacktop,NJDOT State Highway,East,124.0,NaN,No,11868.0,0.000124,1.470588,Impaired-Driving Related,No,40.0,00000124__,NJ 124,Dry,NaN,09:00:00,2,0,0,0,2,NaN,No,Clear,0.000084,No,2023,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24343,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,3724712,No,NaN,No,58,50-59,NaN,NaN,Auto,NaN,13694050,NaN,New Jersey,Not Ejected,"[""Ran Off Road - Right"",""Other Fixed Object""]",NaN,Brown,Unknown,NaN,NaN,NaN,RWJ Barnabas Health - Monmouth Medical Center ...,Front End,Unknown,Fatal Injury (K),Unknown,NaN,NaN,Other Fixed Object,17764758,01,NaN,33412063,Driver,17893503,Illness,NaN,NaN,Front Seat - Right Side,Going Straight Ahead,No,No,Owner,NaN,NaN,Yes,Lap Belt & Harness,Lap Belt & Harness,NaN,Fatal Injury (K),Male,Unknown,New Jersey,New Jersey,NaN,NaN,1.0,NaN,NaN,1.0,No Control Present,13762386,Vehicle,No,No,NaN,NaN,White,13561936,CHEVROLET,NaN,Sport Utility Vehicle,Government,NaN,08735,NJ0151100,No,No,No,No,2096663,No,Ocean,0,7193504,Fixed Object,Yes,2020-11-25T16:55:00.000,2020-11-25,NaN,NJ0151100,NaN,NaN,NaN,15112020-2096663,No,No,N,Other Fixed Object,"{""lon"":-74.30884663,""lat"":40.13723267}","{""lon"":-74.30884663,""lat"":40.13723267}",No,No,Fatal Injury (K),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,40.137233,Dusk,-74.308847,NaN,No,Jackson Twp,"[""Fatal Crashes"",""Total Crashes""]",No,No,No,NaN,NaN,NaN,NaN,NaN,Level,Straight,NaN,Blacktop,Private Property,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Roadway or Lane Departure,Yes,NaN,NaN,MOORES COURT,Dry,20239346.0,16:55:00,0,0,1,0,1,NaN,Yes,Clear,NaN,No,2020,No
24344,"[27,35]","[null,null]","[""Combination"",""Not Deployed""]","[""No"",""Yes""]","[13802032,13802033]","[null,0.2]","[null,""No""]","[null,""Blood""]",NaN,NaN,NaN,NaN,"[""No"",""Yes""]",NaN,"[""No"",""No""]","[""South"",""South""]","[""Yes"",""No""]","[27,35]","[""20-29"",""30-39""]","[""No"",""Yes""]",NaN,"[""Auto"",""Auto""]","[null,null]","[13696058,13696059]","[null,null]","[""New Jersey"",""New Jersey""]","[""Not Ejected"",""Trapped""]","[""MV in Transport"",""Not Applicable"",""Not Appli...","[""Disabling"",""Disabling""]","[""Brown"",""Brown""]","[""Driver Inattention"",""Not Applicable"",""Unknow...",NaN,NaN,"[""No"",""No""]","[""RWJ Barnabas Health - RWJ University Hospita...","[""Front End"",""Rear End""]","[""Entire Body"",""Head""]","[""Suspected Minor Injury (B)"",""Suspected Serio...","[""Contusion/Bruise/Abrasion"",""Internal""]",NaN,NaN,"[""MV in Transport"",""MV in Transport""]","[17767124,17767125]","[""1"",""2""]",NaN,"[33416443,33416444]","[""Driver"",""Driver""]","[17895773,17895774]","[[""Alcohol Use"",""Not Applicable""],[""Unknown"",""...","[""None"",""None""]","[""New Jersey"",""New Jersey""]","[""Driver"",""Driver""]","[""Going Straight Ahead"",""Unknown""]","[""No"",""No""]","[""No"",""No""]","[""Police"",""Police""]","[""Scott's Towing"",""Scott's Towing""]","[""No"",""No""]","[""No"",""No""]","[""Lap Belt & Harness"",""Lap Belt & Harness""]","[""None"",""Unknown""]",25472.0,"[""Suspected Minor Injury (B)"",""Suspected Serio...","[""Female"",""Male""]",NaN,New Jersey,"[""New Jersey"",""New Jersey""]",NaN,NaN,2.0,1.0,NaN,2.0,"[""Lane Markings"",""Lane Markings""]","[13764251,13764252]","[""Vehicle"",""Vehicle""]","[""No"",""Yes""]","[""No"",""No""]",Unknown,"[""None"",""None""]","[""Red"",""Silver""]","[13563775,13563776]","[""DODGE"",""NISSAN""]","[[null,null],[null,null]]","[""Car/Station Wagon/Minivan"",""Sport Utility Ve...","[""Personal"",""Unknown""]",NaN,"[""08004"",""08873""]",NJNSP0000,Yes,No,No,No,B130202402895C,No,Middlesex,0,7194473,Same Direction (Rear End),No,2024-09-08T05:02:00.000,2024-09-08,Sunday,NJNSP0000,Somerville,East,147.0,12162024-B130202402895CPW,No,No,N,MV in Transport,"{""lon"":-74.2888571,""lat"":40.52537056}","{""lon"":-74.28847951,""lat"":40.5258313}",No,No,Suspected Serious Injury (A),655.0,12000655__,Florida Grove Road (MIDDLESEX COUNTY 655),NaN,NaN,NaN,NaN,NaN,No,40.525371,"Dark (street lights on, continuous)",-74.288857,2.85,No,Perth Amboy City,"[""Distracted Driving Related"",""Alcohol Involve...",No,No,No,NaN,NaN,NaN,NaN,NaN,Level,Straight,NaN,Blacktop,NJDOT State Highway,South,440.0,NaN,No,NaN,NaN,0.342516,"[""Distracted Driving Related"",""Impaired-Drivin...",No,55.0,00000440_S,NJ 440 Secondary (Edward J Patten Memorial Hig...,Dry,NaN,05:02:00,2,0,0,0,2,NaN,No,Clear,NaN,No,2024,No